# All makefile fragments assume that $(srcdir) points to the gcc
# directory, not the language subdir
srcdir = /home/lsoave/Docker/TMP/buildroot-2013.05/output/toolchain/gcc-4.7.3/gcc
-include ./gcc-interface/Makefile
-include ../gcc-interface/Makefile
